Change switch statements to if statements to avoid building bugs
Gcc 4.5 issues undefined reference to `__gnu_thumb1_case_uqi' when compiling.
This is a routine which optimizes switch statements in thumb mode when only a
few case statements are present.
Change to "if-else" statements to avoid the issue.

Signed-off-by: Ulf Samuelsson <ulf.samuelsson@atmel.com>
Signed-off-by: Nicolas Ferre <nicolas.ferre@atmel.com>