Makefile: fix ncurses availability check
gcc 14.2 includes -Wimplicit-int, causing the check-lxdialog.sh script
to run into the following compilation error in the check() function:

```
<stdin>:2:1: error: return type defaults to ‘int’ [-Wimplicit-int]
```

This results in the incorrect assumption that ncurses is not available.