driver: pmc: master-clk: fix unwanted operand in ifdef
error: operator '||' has no right operand
  || defined(CONFIG_SAMA5D3X) || defined(CONFIG_SAMA5D4) || \

Fixes: df39a3e44b ("Expect systematic CONFIG_ prefix in config options and preprocessor macros generated by Kconfig")
Signed-off-by: Eugen Hristev <eugen.hristev@microchip.com>