sama5d4ek: non-secure: fix build error
Fix following error, since the _romsize are not defined.

    LD        sama5d4ek-nandflashboot-uboot-3.6.2.elf
  /home/josh/work/at91bootstrap/crt0_gnu.o: In function `reset':
  /home/josh/work/at91bootstrap/crt0_gnu.S:54: undefined reference to
  `_romsize'
  make: ***
  [/home/josh/work/at91bootstrap/binaries/sama5d4ek-nandflashboot-uboot-3.6.2.bin]
  Error 1

To fix this, define the missing _romsize in elf32-littlearm-tz.lds.

Signed-off-by: Josh Wu <josh.wu@atmel.com>