config: fix error when CONFIG_LOAD_NONE is set in non SDCARD configs
non SDCARD configs like CONFIG_FLASH, CONFIG_NANDFLASH or
CONFIG_DATAFLASH use IMG_ADDRESS and IMG_SIZE in init_load_image().
There is no image to load when CONFIG_LOAD_NONE is set, hence
loading image and IMG_ADDRESS/SIZE do not make sense in this
configuration.

Guard init_load_image() when CONFIG_LOAD_NONE is not set and avoid
setting of IMG_ADDRESS, IMG_SIZE and JUMP_ADDR.

Fixes the following error on non sdcard configs:

at91bootstrap/driver/common.c:75:29: error: expected expression before ‘;’ token
  image->offset = IMG_ADDRESS;
                             ^
  CC        /home/atudor/work/at91bootstrap/driver/pmc.c
at91bootstrap/driver/common.c:77:26: error: expected expression before ‘;’ token
  image->length = IMG_SIZE;

Fixes: 803e607d71859 ("Add support for configuring LOAD_NONE - no image after startup")
Signed-off-by: Tudor Ambarus <tudor.ambarus@microchip.com>