driver: mcp16502: use div
Use div() to avoid "undefined reference to __ueabi_uidiv" compilation
error.

Fixes: 9cce315fbe23b ("driver: mcp16502: add driver")
Reported-by: Mihai Sain <mihai.sain@microchip.com>
Signed-off-by: Claudiu Beznea <claudiu.beznea@microchip.com>