undefined reference to `__gnu_thumb1_case_uqi'
To suporting arm-linux-gnueabi-gcc(gcc version 4.6.3)
Gcc issues undefined reference to `__gnu_thumb1_case_uqi' when compiling.
This is a routine which optimizes switch statements in thumb mode
when only a few case statements are present.
Change to "if-else" statements to avoid the issue.

Signed-off-by: Wenyou Yang <wenyou.yang@atmel.com>