include/types.h: conditionally define bool, false and true
include/types.h typedefs ‘bool’ and macro-defines ‘false’ and ‘true’.
However, since C23, these are predefine keywords. As C23 is the default
C dialect for GCC 15, building with this compiler fails with:

    include/types.h:23:23: error: ‘bool’ cannot be defined via ‘typedef’
       23 | typedef unsigned char bool;
          |                       ^~~~
    include/types.h:23:23: note: ‘bool’ is a keyword with ‘-std=c23’ onwards

Fix this build failure by only defining ‘bool’, ‘false’ and ‘true’ on C
dialects older than C23.

Signed-off-by: Edgar Bonet <bonet@grenoble.cnrs.fr>